{ pkgs, ... }: {
  environment = {
    systemPackages = with pkgs; [
      apngopt
      bundle2jwks
      cached-nix-shell
      cachix
      cmake
      unstable.datalad
      dig
      file
      gnupg
      home-manager
      iftop
      jq
      killall
      lm_sensors
      lsof
      lsyncd
      micromamba
      nil
      nixpkgs-fmt
      nixos-generators
      nix-index
      nix-tree
      openssl
      unstable.packer
      pciutils
      unstable.pixi
      pkg-config
      pre-commit
      pv
      ripgrep-all
      unstable.ruff
      sops
      tree
      usbutils
      unzip
      wget
      zsh
      zulu
    ];
  };
}
